/* ================================================================
   POMPEY FURNITURE COMPANY — BUSINESS REPORTING QUERIES

   Run these standalone PostgreSQL queries in pgAdmin or psql after
   creating the schema and sample data. They are reporting queries,
   not application API queries, so $1/$2 parameters are not required.
   ================================================================ */

/* QUERY 1: MONTHLY INCOME FROM SHOWROOM PICKUP ORDERS

   Purpose:
   Calculate and compare monthly income generated by orders collected
   from each showroom. */
SELECT
  s.name AS showroom_name,
  DATE_TRUNC('month', o.order_date)::date AS month,
  SUM(oi.unit_price * oi.quantity) AS monthly_income
FROM "order" AS o
JOIN order_item AS oi ON oi.order_id = o.order_id
JOIN delivery_info AS d ON d.order_id = o.order_id
JOIN showroom AS s ON s.showroom_id = d.showroom_id
WHERE d.delivery_type = 'pickup'
GROUP BY
  s.showroom_id,
  s.name,
  DATE_TRUNC('month', o.order_date)
ORDER BY s.name, month;

/* QUERY 2: PRODUCTS AVAILABLE WITHIN A PRICE RANGE

   Change 500.00 and 800.00 to test another price range. */
SELECT
  p.name AS product_name,
  s.name AS showroom_name,
  p.price,
  sa.quantity
FROM product AS p
JOIN stock_availability AS sa ON sa.product_id = p.product_id
JOIN showroom AS s ON s.showroom_id = sa.showroom_id
WHERE p.price BETWEEN 500.00 AND 800.00
  AND sa.quantity > 0
ORDER BY s.name, p.price, p.name;

/* QUERY 3: DELIVERY TYPE SUMMARY */
SELECT
  d.delivery_type,
  COUNT(*) AS total_deliveries
FROM delivery_info AS d
GROUP BY d.delivery_type
ORDER BY d.delivery_type;

/* QUERY 4: CUSTOMERS WITH RETURNS IN THE LAST 28 DAYS */
SELECT
  c.name AS customer_name,
  r.return_date,
  r.reason,
  o.order_id
FROM customer AS c
JOIN "order" AS o ON o.customer_id = c.customer_id
JOIN return_record AS r ON r.order_id = o.order_id
WHERE r.return_date >= CURRENT_DATE - INTERVAL '28 days'
ORDER BY r.return_date DESC;
